// docs.go generated by swag. DO NOT EDIT.
//
// This file is the main configuration file for the Swagger documentation.
// It contains all the metadata and configuration for the API documentation.
//
// For more information about this file, see https://github.com/swaggo/swag#general-api-info
//
// @title           LKE Application API
// @version         1.4.11.1
// @description     API for LKE (Lembar Kerja Evaluasi) Application - Indonesian Government Evaluation System
// @termsOfService  http://swagger.io/terms
// @contact.name   API Support
// @contact.email  support@lke-app.com
// @license.name  MIT License
// @license.url   https://opensource.org/licenses/MIT
// @host          localhost:8080
// @BasePath       /v1
// @schemes        http https
// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization

package main
